# Generated by Django 3.2.8 on 2021-11-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='username',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
