# Generated by Django 3.2.8 on 2021-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='password',
            field=models.CharField(max_length=222),
        ),
    ]
