# Generated by Django 3.2.8 on 2021-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companymodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=122)),
                ('address', models.CharField(help_text='Address', max_length=322)),
                ('city', models.CharField(max_length=123)),
                ('postalcode', models.IntegerField(help_text='Postal Code')),
                ('modile', models.IntegerField()),
                ('signation', models.CharField(max_length=44)),
                ('branch', models.CharField(max_length=44)),
                ('rank', models.CharField(max_length=10)),
                ('basic_pay', models.IntegerField()),
                ('bank_account', models.CharField(max_length=44)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
