# Generated by Django 3.2.8 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_addemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='address',
            field=models.CharField(max_length=322),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='addemployee',
            name='postalcode',
            field=models.IntegerField(),
        ),
    ]
