# Generated by Django 3.2.8 on 2021-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20211202_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(help_text='Name', max_length=122),
        ),
    ]
